version: 1.0.{build}
configuration: Release
image: Visual Studio 2017
before_build:
- ps: >-
    dotnet restore
build:
  verbosity: minimal
test_script:
- cmd: dotnet test .\src\Shodan.Net.UnitTests\Shodan.Net.UnitTests.csproj